# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3453058a395189f5e8762e6225a420585eb4cf46f8a1f2a31727b70416ab7b02f80c575af0fb24deaff5282adce8d0e2a467b258e5ed4f57f71627bee6668f4a

test:
  secret_key_base: c73ab37b32402cc31e141508a6d4f76ae9aad60588ab4404a35b537949946b9c424b775eed94ab0d4faa2daa71b7882c1ec3e98981849984480a67cd545a7071

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
